name: life_os
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  http: ^1.1.2

  cupertino_icons: ^1.0.8
  speech_to_text: ^7.3.0

  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  cloud_functions: ^6.0.5
  firebase_storage: ^13.0.6
  image_picker: ^1.1.1
  file_picker: ^8.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/courseConfigs/
